{{- if or .Values.protectedAlpha.enabled .Values.protectedAlpha.prepare }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spurfire-control.fullname" . }}-broker
  labels:
    {{- include "spurfire-control.brokerLabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
